- name: Get host IP
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  tags: metricbeat


# - name: "Download metricbeat"
#   get_url:
#     url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.4.2-x86_64.rpm
# - name: "Install metricbeat"
#   command: sudo rpm -vi metricbeat-6.4.2-x86_64.rpm
- name: install metricbeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.4.2-x86_64.rpm
    state: present
- name: install auditbeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-6.5.1-x86_64.rpm
    state: present
- name: Add configuration to metricbeat
  blockinfile:
    dest: /etc/metricbeat/metricbeat.yml
    block: |
      metricbeat.modules:
      - module: system
      metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      #- core           # Per CPU core usage
      #- diskio         # Disk IO
      #- filesystem     # File system usage for each mountpoint
      #- fsstat         # File system summary metrics
      #- raid           # Raid
      - socket         # Sockets and connection info (linux only)
      enabled: true
      period: 10s
      processes: ['.*']
      # Configure the metric types that are included by these metricsets.
      cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
      core.metrics: ["percentages"]  # The other available option is ticks.
      output.elasticsearch:
        hosts: ["{{ metricbeat_ip }}:9200"]
      setup.kibana:
        host: "{{ metricbeat_ip }}:5601"
- name: Start service metricbeat
  service:
    name: metricbeat.service
    state: started      
    enabled: yes
- name: Add configuration to auditbeat
  blockinfile:
    dest: /etc/auditbeat/auditbeat.yml
    block: |
      auditbeat.modules:
      - module: auditd
        audit_rules: |
          # Things that affect identity.
          -w /etc/group -p wa -k identity
          -w /etc/passwd -p wa -k identity
          -w /etc/gshadow -p wa -k identity
          -w /etc/shadow -p wa -k identity

          # Unauthorized access attempts to files (unsuccessful).
          -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -F key=access
          -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -F key=access
          -a always,exit -F arch=b64 -S open,truncate,ftruncate,creat,openat,open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -F key=access
          -a always,exit -F arch=b64 -S open,truncate,ftruncate,creat,openat,open_by_handle_at -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -F key=access
      - module: file_integrity
        paths:
          - /bin
          - /usr/bin
          - /sbin
          - /usr/sbin
          - /etc
      setup.kibana:
      output.elasticsearch:
        # Array of hosts to connect to.
        hosts: ["{{ metricbeat_ip }}:9200"]
      processors:
        - add_host_metadata: ~
        - add_cloud_metadata: ~
- name: Start service auditbeat
  service:
    name: auditbeat.service
    state: started      
    enabled: yes
