- name: import rpm key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: install java
  yum:
    name: jre
    state: latest
- name: Copy elasticsearch repo file
  copy:
    src: templates/elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644
- name: Copy kibana repo file
  copy:
    src: templates/kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    owner: root
    group: root
    mode: 0644
- name: install elasticsearch
  yum:
    name: elasticsearch
    state: latest
- name: install kibana
  yum:
    name: kibana
    state: latest
- name: add external access to elasticsearch config
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'network.host: 0.0.0.0'
    insertbefore: BOF
- name: change elasticsearch clustername
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'cluster.name: Green.local'
    insertbefore: BOF
- name: add external access to kibana config
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: 'server.host: 0.0.0.0'
    insertbefore: BOF
- name: Link kibana to elasticsearch
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: 'elasticsearch.url: "http://localhost:9200"'
    insertbefore: BOF
- name: Start service kibana
  service:
    name: kibana.service
    state: started      
    enabled: yes
- name: Start service elasticsearch
  service:
    name: elasticsearch.service
    state: started   
    enabled: yes
- name: install metricbeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.4.2-x86_64.rpm
    state: present
- name: Add modules to metricbeat
  blockinfile:
    dest: /etc/metricbeat/metricbeat.yml
    block: |
      metricbeat.modules:
      - module: system
      metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      #- core           # Per CPU core usage
      #- diskio         # Disk IO
      #- filesystem     # File system usage for each mountpoint
      #- fsstat         # File system summary metrics
      #- raid           # Raid
      - socket         # Sockets and connection info (linux only)
      enabled: true
      period: 10s
      processes: ['.*']
      # Configure the metric types that are included by these metricsets.
      cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
      core.metrics: ["percentages"]  # The other available option is ticks.
      output.elasticsearch:
        hosts: ["localhost:9200"]
      setup.kibana:
        host: "localhost:5601"
- name: Start service metricbeat
  service:
    name: metricbeat.service
    state: started      
    enabled: yes
- name: Waiting for port 5601 to become open on the host
  wait_for:
    port: 5601
    delay: 30
- name: enable metricbeat dashboards
  command: metricbeat setup --dashboards
- name: install packetbeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-6.4.2-x86_64.rpm
    state: present
- name: Add modules to packetbeat
  blockinfile:
    dest: /etc/packetbeat/packetbeat.yml
    block: |
         packetbeat.interfaces.device: any
         output.elasticsearch:
           hosts: ["localhost:9200"]
         setup.kibana:
           host: "localhost:5601"
- name: Start service packetbeat
  systemd:
    name: packetbeat
    enabled: yes
- name: enable the packetbeat dashboards
  command: packetbeat setup --dashboards
